
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS MODULO NUMBER PLUS RPAREN TIMESexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : term MODULO factorterm : factorfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'NUMBER':([0,5,6,7,8,9,10,],[4,4,4,4,4,4,4,]),'LPAREN':([0,5,6,7,8,9,10,],[5,5,5,5,5,5,5,]),'$end':([1,2,3,4,12,13,14,15,16,17,],[0,-3,-7,-8,-1,-2,-4,-5,-6,-9,]),'PLUS':([1,2,3,4,11,12,13,14,15,16,17,],[6,-3,-7,-8,6,-1,-2,-4,-5,-6,-9,]),'MINUS':([1,2,3,4,11,12,13,14,15,16,17,],[7,-3,-7,-8,7,-1,-2,-4,-5,-6,-9,]),'RPAREN':([2,3,4,11,12,13,14,15,16,17,],[-3,-7,-8,17,-1,-2,-4,-5,-6,-9,]),'TIMES':([2,3,4,12,13,14,15,16,17,],[8,-7,-8,8,8,-4,-5,-6,-9,]),'DIVIDE':([2,3,4,12,13,14,15,16,17,],[9,-7,-8,9,9,-4,-5,-6,-9,]),'MODULO':([2,3,4,12,13,14,15,16,17,],[10,-7,-8,10,10,-4,-5,-6,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,],[1,11,]),'term':([0,5,6,7,],[2,2,12,13,]),'factor':([0,5,6,7,8,9,10,],[3,3,3,3,14,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','expr_parser.py',9),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','expr_parser.py',13),
  ('expression -> term','expression',1,'p_expression_term','expr_parser.py',17),
  ('term -> term TIMES factor','term',3,'p_term_times','expr_parser.py',21),
  ('term -> term DIVIDE factor','term',3,'p_term_div','expr_parser.py',25),
  ('term -> term MODULO factor','term',3,'p_term_modulo','expr_parser.py',29),
  ('term -> factor','term',1,'p_term_factor','expr_parser.py',33),
  ('factor -> NUMBER','factor',1,'p_factor_num','expr_parser.py',37),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','expr_parser.py',41),
]
