
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE ENDL IDENTIFIER LPAREN MINUS MODULO NUMBER PLUS RPAREN TIMESexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : term MODULO factorterm : factorterm : IDENTIFIER LPAREN RPARENfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'IDENTIFIER':([0,5,7,8,],[4,4,4,4,]),'NUMBER':([0,5,7,8,9,10,11,],[6,6,6,6,6,6,6,]),'LPAREN':([0,4,5,7,8,9,10,11,],[5,12,5,5,5,5,5,5,]),'$end':([1,2,3,6,14,15,16,17,18,19,20,],[0,-3,-7,-9,-1,-2,-4,-5,-6,-8,-10,]),'PLUS':([1,2,3,6,13,14,15,16,17,18,19,20,],[7,-3,-7,-9,7,-1,-2,-4,-5,-6,-8,-10,]),'MINUS':([1,2,3,6,13,14,15,16,17,18,19,20,],[8,-3,-7,-9,8,-1,-2,-4,-5,-6,-8,-10,]),'RPAREN':([2,3,6,12,13,14,15,16,17,18,19,20,],[-3,-7,-9,19,20,-1,-2,-4,-5,-6,-8,-10,]),'TIMES':([2,3,6,14,15,16,17,18,19,20,],[9,-7,-9,9,9,-4,-5,-6,-8,-10,]),'DIVIDE':([2,3,6,14,15,16,17,18,19,20,],[10,-7,-9,10,10,-4,-5,-6,-8,-10,]),'MODULO':([2,3,6,14,15,16,17,18,19,20,],[11,-7,-9,11,11,-4,-5,-6,-8,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,],[1,13,]),'term':([0,5,7,8,],[2,2,14,15,]),'factor':([0,5,7,8,9,10,11,],[3,3,3,3,16,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','expr_parser.py',14),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','expr_parser.py',18),
  ('expression -> term','expression',1,'p_expression_term','expr_parser.py',22),
  ('term -> term TIMES factor','term',3,'p_term_times','expr_parser.py',26),
  ('term -> term DIVIDE factor','term',3,'p_term_div','expr_parser.py',30),
  ('term -> term MODULO factor','term',3,'p_term_modulo','expr_parser.py',34),
  ('term -> factor','term',1,'p_term_factor','expr_parser.py',38),
  ('term -> IDENTIFIER LPAREN RPAREN','term',3,'p_term_function','expr_parser.py',42),
  ('factor -> NUMBER','factor',1,'p_factor_num','expr_parser.py',46),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','expr_parser.py',50),
]
